const Papa = require('papaparse');
const XLSX = require('xlsx');
const PDFDocument = require('pdfkit');
const PptxGenJS = require('pptxgenjs');

// ─── Cleaned Dataset ──────────────────────────────────────────────────────────
function buildCleanedCsv(rows, fields) {
  return Papa.unparse({ fields, data: rows.map(r => fields.map(f => r[f] ?? '')) });
}

function buildCleanedXlsx(rows, fields) {
  const ws = XLSX.utils.json_to_sheet(rows, { header: fields });
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Cleaned Data');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// ─── Shared PDF helpers ───────────────────────────────────────────────────────
const COLORS = {
  violet: '#6366f1',
  cyan: '#0891b2',
  emerald: '#059669',
  amber: '#d97706',
  rose: '#e11d48',
  dark: '#14142b',
  muted: '#5a5a7a',
  border: '#e2e2f0',
};

function pdfHeader(doc, title, subtitle) {
  doc.rect(0, 0, doc.page.width, 90).fill(COLORS.dark);
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(22).text(title, 50, 28);
  if (subtitle) {
    doc.fillColor('#c7c7e0').font('Helvetica').fontSize(11).text(subtitle, 50, 58);
  }
  doc.fillColor(COLORS.dark);
  doc.y = 120;
}

function pdfSectionTitle(doc, text) {
  doc.moveDown(0.5);
  doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.dark).text(text);
  doc.moveTo(50, doc.y + 4).lineTo(doc.page.width - 50, doc.y + 4).strokeColor(COLORS.border).stroke();
  doc.moveDown(0.8);
}

// ─── Dashboard Report PDF ─────────────────────────────────────────────────────
function buildDashboardPdf({ fileName, healthScore, dashboardType, kpis, categoryBreakdown, valueColumn, categoryColumn }) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks = [];
  doc.on('data', c => chunks.push(c));

  pdfHeader(doc, 'Dashboard Report', `${fileName} — ${dashboardType ? dashboardType.charAt(0).toUpperCase() + dashboardType.slice(1) : ''} view`);

  pdfSectionTitle(doc, 'Key Metrics');
  (kpis || []).forEach(k => {
    doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.dark).text(`${k.label}:  `, { continued: true });
    doc.font('Helvetica').fillColor(COLORS.violet).text(`${k.value}  `, { continued: true });
    if (k.change) {
      doc.fillColor(k.trend === 'up' ? COLORS.emerald : COLORS.rose).text(`(${k.change})`);
    } else {
      doc.text('');
    }
  });

  if (categoryBreakdown && categoryBreakdown.length > 0) {
    pdfSectionTitle(doc, `${valueColumn || 'Value'} by ${categoryColumn || 'Category'}`);
    const maxVal = Math.max(...categoryBreakdown.map(c => c.value)) || 1;
    categoryBreakdown.slice(0, 10).forEach(c => {
      const barWidth = (c.value / maxVal) * 350;
      const y = doc.y;
      doc.font('Helvetica').fontSize(10).fillColor(COLORS.dark).text(String(c.name), 50, y, { width: 120 });
      doc.rect(180, y, Math.max(barWidth, 2), 12).fill(COLORS.violet);
      doc.fillColor(COLORS.dark).fontSize(9).text(c.value.toLocaleString(), 180 + Math.max(barWidth, 2) + 8, y);
      doc.y = y + 20;
    });
  }

  pdfSectionTitle(doc, 'Dataset Health');
  doc.font('Helvetica').fontSize(11).fillColor(COLORS.dark).text(`Overall health score: ${healthScore} / 100`);

  doc.moveDown(2);
  doc.fontSize(8).fillColor(COLORS.muted).text('Generated by DataAnalyst AI', 50, doc.page.height - 50);

  doc.end();
  return new Promise(resolve => doc.on('end', () => resolve(Buffer.concat(chunks))));
}

// ─── AI Insights PDF ──────────────────────────────────────────────────────────
function buildInsightsPdf({ fileName, summary, findings }) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks = [];
  doc.on('data', c => chunks.push(c));

  pdfHeader(doc, 'AI Insights Report', fileName);

  pdfSectionTitle(doc, 'Executive Summary');
  doc.font('Helvetica').fontSize(11).fillColor(COLORS.dark).text(summary || 'No summary available.', { align: 'left', lineGap: 3 });

  pdfSectionTitle(doc, 'Key Findings');
  (findings || []).forEach((f, i) => {
    if (doc.y > doc.page.height - 140) doc.addPage();
    doc.font('Helvetica-Bold').fontSize(12).fillColor(COLORS.violet).text(`${i + 1}. ${f.title}`);
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.dark).text(f.description, { lineGap: 2 });
    doc.font('Helvetica-Oblique').fontSize(9).fillColor(COLORS.muted).text(`AI confidence: ${f.confidence}%`);
    doc.moveDown(0.8);
  });

  doc.fontSize(8).fillColor(COLORS.muted).text('Generated by DataAnalyst AI', 50, doc.page.height - 50);

  doc.end();
  return new Promise(resolve => doc.on('end', () => resolve(Buffer.concat(chunks))));
}

// ─── Presentation Deck (PPTX) ─────────────────────────────────────────────────
async function buildPresentationPptx({ fileName, healthScore, kpis, findings, dashboardType }) {
  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 });
  pptx.layout = 'WIDE';

  const VIOLET = '6366F1';
  const DARK = '14142B';
  const MUTED = '5A5A7A';

  // Title slide
  let slide = pptx.addSlide();
  slide.background = { color: DARK };
  slide.addText('DataAnalyst AI', { x: 0.6, y: 2.6, w: 12, h: 1, fontSize: 40, bold: true, color: 'FFFFFF', fontFace: 'Arial' });
  slide.addText(`Analysis Report — ${fileName}`, { x: 0.6, y: 3.5, w: 12, h: 0.6, fontSize: 18, color: 'C7C7E0' });
  slide.addText(`${dashboardType ? dashboardType.charAt(0).toUpperCase() + dashboardType.slice(1) : 'Executive'} View`, { x: 0.6, y: 4.1, w: 12, h: 0.5, fontSize: 14, color: VIOLET });

  // KPI slide
  slide = pptx.addSlide();
  slide.addText('Key Metrics', { x: 0.5, y: 0.4, fontSize: 28, bold: true, color: DARK });
  const kpiList = kpis || [];
  const colW = 11.8 / Math.max(kpiList.length, 1);
  kpiList.forEach((k, i) => {
    const x = 0.6 + i * colW;
    slide.addShape(pptx.ShapeType.roundRect, { x, y: 1.4, w: colW - 0.3, h: 1.6, fill: { color: 'F4F4FC' }, line: { color: 'E2E2F0' }, rectRadius: 0.1 });
    slide.addText(k.value, { x, y: 1.6, w: colW - 0.3, h: 0.6, fontSize: 22, bold: true, color: VIOLET, align: 'center' });
    slide.addText(k.label, { x, y: 2.3, w: colW - 0.3, h: 0.5, fontSize: 11, color: MUTED, align: 'center' });
  });
  slide.addText(`Dataset health score: ${healthScore} / 100`, { x: 0.6, y: 3.6, fontSize: 14, color: DARK });

  // Insight slides (one finding per slide, up to 6)
  (findings || []).slice(0, 6).forEach((f, i) => {
    const s = pptx.addSlide();
    s.addText(`Insight ${i + 1}`, { x: 0.6, y: 0.4, fontSize: 14, color: VIOLET, bold: true });
    s.addText(f.title, { x: 0.6, y: 0.9, w: 12, fontSize: 26, bold: true, color: DARK });
    s.addText(f.description, { x: 0.6, y: 2.0, w: 11.5, fontSize: 16, color: '333344', lineSpacing: 24 });
    s.addText(`AI confidence: ${f.confidence}%`, { x: 0.6, y: 6.6, fontSize: 12, color: MUTED });
  });

  return pptx.write({ outputType: 'nodebuffer' });
}

module.exports = { buildCleanedCsv, buildCleanedXlsx, buildDashboardPdf, buildInsightsPdf, buildPresentationPptx };
